CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    username VARCHAR(50) NOT NULL COMMENT '登录账号',
    password VARCHAR(100) NOT NULL COMMENT '密码',
    real_name VARCHAR(50) NOT NULL COMMENT '真实姓名',
    role VARCHAR(20) NOT NULL COMMENT '角色',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '账号状态',
    student_no VARCHAR(30) NULL COMMENT '学号',
    college VARCHAR(100) NULL COMMENT '学院',
    major VARCHAR(100) NULL COMMENT '专业',
    grade VARCHAR(20) NULL COMMENT '年级',
    class_name VARCHAR(50) NULL COMMENT '班级',
    phone VARCHAR(20) NULL COMMENT '手机号',
    email VARCHAR(100) NULL COMMENT '邮箱',
    avatar VARCHAR(255) NULL COMMENT '头像',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE IF NOT EXISTS intern_project (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    title VARCHAR(200) NOT NULL COMMENT '项目标题',
    description TEXT NULL COMMENT '项目描述',
    teacher_id BIGINT NOT NULL COMMENT '教师ID',
    company VARCHAR(200) NULL COMMENT '实习单位',
    location VARCHAR(200) NULL COMMENT '实习地点',
    max_students INT NOT NULL DEFAULT 0 COMMENT '最大招收人数',
    college_limit VARCHAR(100) NULL COMMENT '限定学院',
    grade_limit VARCHAR(20) NULL COMMENT '限定年级',
    start_date DATE NULL COMMENT '开始日期',
    end_date DATE NULL COMMENT '结束日期',
    enroll_deadline DATE NULL COMMENT '报名截止',
    semester VARCHAR(30) NULL COMMENT '学期',
    credit_type VARCHAR(50) NULL COMMENT '学分类型',
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' COMMENT '项目状态',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_teacher (teacher_id),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实习项目表';

CREATE TABLE IF NOT EXISTS intern_application (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    project_id BIGINT NOT NULL COMMENT '项目ID',
    student_id BIGINT NOT NULL COMMENT '学生ID',
    apply_reason TEXT NULL COMMENT '申请理由',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '审批状态',
    review_comment VARCHAR(500) NULL COMMENT '审批意见',
    reviewed_by BIGINT NULL COMMENT '审批人',
    reviewed_at DATETIME NULL COMMENT '审批时间',
    phase VARCHAR(20) NOT NULL DEFAULT 'ENROLLED' COMMENT '实习阶段',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_student (project_id, student_id),
    KEY idx_student (student_id),
    KEY idx_project (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实习申请表';

CREATE TABLE IF NOT EXISTS intern_journal (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    application_id BIGINT NOT NULL COMMENT '申请ID',
    student_id BIGINT NOT NULL COMMENT '学生ID',
    title VARCHAR(200) NOT NULL COMMENT '标题',
    content TEXT NOT NULL COMMENT '内容',
    journal_type VARCHAR(20) NOT NULL DEFAULT 'DAILY' COMMENT '日志类型',
    journal_date DATE NOT NULL COMMENT '日志日期',
    week_no INT NULL COMMENT '周次',
    teacher_comment VARCHAR(1000) NULL COMMENT '教师批注',
    score DECIMAL(5,2) NULL COMMENT '评分',
    scored_at DATETIME NULL COMMENT '评分时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_journal_app (application_id),
    KEY idx_journal_student (student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实习日志表';

CREATE TABLE IF NOT EXISTS intern_report (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    application_id BIGINT NOT NULL COMMENT '申请ID',
    student_id BIGINT NOT NULL COMMENT '学生ID',
    title VARCHAR(200) NOT NULL COMMENT '标题',
    summary TEXT NULL COMMENT '摘要',
    file_url VARCHAR(500) NOT NULL COMMENT '文件路径',
    semester VARCHAR(30) NULL COMMENT '学期',
    credit_type VARCHAR(50) NULL COMMENT '学分类型',
    status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED' COMMENT '状态',
    teacher_comment VARCHAR(1000) NULL COMMENT '教师评语',
    teacher_score DECIMAL(5,2) NULL COMMENT '教师评分',
    is_excellent TINYINT NOT NULL DEFAULT 0 COMMENT '是否优秀',
    ai_flag VARCHAR(50) NULL COMMENT 'AI 标记',
    reviewed_by BIGINT NULL COMMENT '评阅教师',
    reviewed_at DATETIME NULL COMMENT '评阅时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_report_app (application_id),
    KEY idx_report_student (student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实习报告表';

CREATE TABLE IF NOT EXISTS intern_grade (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    application_id BIGINT NOT NULL COMMENT '申请ID',
    student_id BIGINT NOT NULL COMMENT '学生ID',
    teacher_id BIGINT NOT NULL COMMENT '教师ID',
    journal_score DECIMAL(5,2) NOT NULL DEFAULT 0 COMMENT '日志成绩',
    report_score DECIMAL(5,2) NOT NULL DEFAULT 0 COMMENT '报告成绩',
    final_score DECIMAL(5,2) NOT NULL DEFAULT 0 COMMENT '总评成绩',
    teacher_comment VARCHAR(1000) NULL COMMENT '教师评语',
    admin_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '管理员审核状态',
    admin_comment VARCHAR(1000) NULL COMMENT '管理员意见',
    confirmed_by BIGINT NULL COMMENT '终审人',
    confirmed_at DATETIME NULL COMMENT '终审时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_grade_application (application_id),
    KEY idx_grade_student (student_id),
    KEY idx_grade_teacher (teacher_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='成绩表';

CREATE TABLE IF NOT EXISTS sys_attachment (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    ref_type VARCHAR(30) NOT NULL COMMENT '关联类型',
    ref_id BIGINT NOT NULL DEFAULT 0 COMMENT '关联ID',
    original_name VARCHAR(255) NOT NULL COMMENT '原文件名',
    stored_name VARCHAR(255) NOT NULL COMMENT '存储文件名',
    file_url VARCHAR(500) NOT NULL COMMENT '文件路径',
    file_size BIGINT NULL COMMENT '文件大小',
    content_type VARCHAR(100) NULL COMMENT '文件类型',
    create_by BIGINT NULL COMMENT '上传人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_attachment_ref (ref_type, ref_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='附件表';
